from __future__ import annotations

import re
from typing import Any

from app.plugins.base import ExecutionContext, ExecutionResult, LLMProviderPlugin, NormalizedPayload


class MockProviderPlugin(LLMProviderPlugin):
    async def healthcheck(self) -> dict[str, Any]:
        return {
            'ok': True,
            'message': 'Mock provider ready (no credentials required)',
            'provider': 'mock_provider',
        }

    async def invoke(self, request: dict[str, Any], context: ExecutionContext) -> ExecutionResult:
        model = request.get('model') or self.config.get('default_model') or 'mock-echo-v1'
        messages = request.get('messages') or []
        prompt = (request.get('input') or '').strip()
        system_prompt = (request.get('system_prompt') or '').strip()
        if messages:
            system_prompt = system_prompt or self._find_system_prompt(messages)
            prompt = self._messages_to_prompt(messages)
        synthesized = self._build_response(prompt=prompt, system_prompt=system_prompt, model=model)
        payload = NormalizedPayload(
            type='text_bundle',
            title='Mock LLM output',
            items=[{'name': 'mock-response.md', 'text': synthesized}],
            metadata={'provider': 'mock_provider', 'model': model},
        )
        prompt_tokens = max(1, len((system_prompt + '\n' + prompt).split()))
        completion_tokens = max(1, len(synthesized.split()))
        return ExecutionResult(
            status='success',
            summary='Mock provider invocation completed',
            payload=payload,
            metrics={
                'latency_ms': 12,
                'prompt_tokens': prompt_tokens,
                'completion_tokens': completion_tokens,
                'total_tokens': prompt_tokens + completion_tokens,
                'finish_reason': 'mock_complete',
            },
            raw={
                'provider': 'mock_provider',
                'model': model,
                'status': 'completed',
                'output_text': synthesized,
                'usage': {
                    'prompt_tokens': prompt_tokens,
                    'completion_tokens': completion_tokens,
                    'total_tokens': prompt_tokens + completion_tokens,
                },
            },
        )

    def _build_response(self, prompt: str, system_prompt: str, model: str) -> str:
        preview = prompt[:900].strip() or '(empty prompt)'
        bullets = self._extract_bullets(prompt)
        bullet_text = '\n'.join(f'- {item}' for item in bullets) if bullets else '- No obvious bullet points detected; this is a synthetic smoke-test response.'
        sys_note = f'System prompt detected: {system_prompt[:160]}' if system_prompt else 'No system prompt supplied.'
        return (
            f'# Mock Provider Response\n\n'
            f'Model: `{model}`\n\n'
            f'{sys_note}\n\n'
            f'## Interpreted highlights\n{bullet_text}\n\n'
            f'## Prompt preview\n{preview}\n\n'
            f'## Why this exists\n'
            'This response is generated by the built-in mock provider so you can verify provider setup, '
            'prompt rendering, workbench execution, audit logging, and UI display without credentials.'
        )

    def _extract_bullets(self, prompt: str) -> list[str]:
        candidates = []
        for line in prompt.splitlines():
            cleaned = line.strip()
            if not cleaned:
                continue
            if cleaned.startswith(('-', '*')) or re.match(r'^\d+[.)]\s+', cleaned):
                candidates.append(re.sub(r'^([-*]|\d+[.)])\s*', '', cleaned))
            elif len(candidates) < 3 and len(cleaned) > 24:
                candidates.append(cleaned[:140])
            if len(candidates) >= 4:
                break
        return candidates[:4]

    def _messages_to_prompt(self, messages: list[dict[str, Any]]) -> str:
        chunks = []
        for message in messages:
            role = message.get('role', 'user')
            if role == 'system':
                continue
            chunks.append(f"{role.upper()}: {message.get('content', '')}")
        return '\n'.join(chunks).strip()

    def _find_system_prompt(self, messages: list[dict[str, Any]]) -> str:
        for message in messages:
            if message.get('role') == 'system':
                return str(message.get('content', '')).strip()
        return ''
